backend:
  name: git-gateway
  repo: phamquang2024/CONG_TY_VI_TINH_QUOC_VIET
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Sản phẩm"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tên sản phẩm", name: "title", widget: "string" }
      - { label: "Danh mục", name: "category", widget: "select", options: ["may-tinh", "may-in", "mang-lan", "camera"] }
      - { label: "Thông số kỹ thuật tóm tắt", name: "specs", widget: "string" }
      - { label: "Giá bán (VNĐ)", name: "price", widget: "string" }
      - { label: "Hình ảnh sản phẩm", name: "image", widget: "image" }
